/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ccc.ccclient_end;

public final class Manifest {
    public static final class permission {
        /**  极光推送需要的权限  开始 
 Required 
         */
        public static final String JPUSH_MESSAGE="com.ccc.ccclient_end.permission.JPUSH_MESSAGE";
    }
}
